### ISSUE TITLE
The size of tensor a (83597) must match the size of tensor b (1103547) at non-singleton dimension 1

### ISSUE THREAD

**Issue by dlopez-bioinfo** [AI-sandbox/SALAI-Net#2]
Hi,

I'd like to find the main population ancestry in a sample. To do this, I've tried the following command:

```
$> python ../SALAI-Net/src/SALAI.py \
  --model-cp ../SALAI-Net/models/hapmap_model/models/best_model.pth \
  -q european_test.vcf \
  -r ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz  \
  -m 1kg.map \
  -o prediction_folder

Namespace(model_cp='../SALAI-Net/models/hapmap_model/models/best_model.pth', model_args=None, test_mixed=False, ref_panel=False, query='european_test.vcf', reference='ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz', map='1kg.map', out_folder='prediction_folder', batch_size=16)
No dropout
Loading data from .vcf file ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
10 182
9 198
6 210
22 208
3 186
7 188
13 214
20 170
21 192
16 198
0 192
12 226
8 198
2 172
18 170
23 204
14 204
4 198
25 216
5 206
15 208
17 198
1 122
19 128
24 214
11 206
Traceback (most recent call last):
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/1kg_test/../SALAI-Net/src/SALAI.py", line 69, in <module>
    predicted_classes, predicted_classes_window, ibd = inference(model, test_loader, args)
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/src/stepsagnostic/traintest.py", line 144, in inference
    output = model(batch["mixed_vcf"], batch["ref_panel"])
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/src/models/lai_models.py", line 213, in forward
    out, max_indices = self.base_model(input_mixed, ref_panel)
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/src/models/lai_models.py", line 162, in forward
    out = self.inpref_oper(input_mixed, ref_panel)
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/src/models/lai_models.py", line 263, in forward
    out.append(multiply_ref_panel(inp, ref))
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/src/models/lai_models.py", line 247, in multiply_ref_panel
    out = {
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/src/models/lai_models.py", line 248, in <dictcomp>
    ancestry: mixed.unsqueeze(0) * ref_panel[ancestry] for ancestry in ref_panel.keys()
RuntimeError: The size of tensor a (83597) must match the size of tensor b (1103547) at non-singleton dimension 1
```

where

- `ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz` is the 1000 genomes project ch22 vcf file downloaded from [here](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz). I assumed that the smallest chromosome is enough for this task (but not sure)
- `1kg.map` contains the 1kg samples and populations
- and `european_test.vcf`is the clinical exome (~5000 genes) I'd like to test.

I've tried the full `european_test.vcf` file as well as the chr22 subset, but in both cases I get the same error. What could be the reason for this error? 

I appreciate any help :)

**Comment by benoriol** [comment]
Hi, thank you for raising the issue.

Can you tell me what's the number of snps available in `european_test.vcf` for chm22 subset and also for `ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz` ?

Benet

**Comment by dlopez-bioinfo** [comment]
Thank you very much for your response. 
The files had 83597 and 1103547 snps. I filtered both files so that I have now the same SNPs and now I'm getting the following error:
```
Traceback (most recent call last):
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/1kg_test/../SALAI-Net/src/SALAI.py", line 69, in <module>
    predicted_classes, predicted_classes_window, ibd = inference(model, test_loader, args)
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/src/stepsagnostic/traintest.py", line 141, in inference
    for i, batch in enumerate(test_loader):
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/src/dataloaders/genome_datasets.py", line 228, in __getitem__
    item["ref_panel"], item['reference_names'], item['reference_idx'] = self.reference_panel.sample_reference_panel()
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/src/dataloaders/genome_datasets.py", line 168, in sample_reference_panel
    return self.sample_uniform_all_classes(n_sample_per_class=self.n_refs_per_class)
  File "/mnt/lustre/home/dlopez/projects/SALAI-Net/SALAI-Net/src/dataloaders/genome_datasets.py", line 157, in sample_uniform_all_classes
    reference_samples[ancestry].append(self.reference_vcf[i])
IndexError: index 5008 is out of bounds for axis 0 with size 5008
```

**Comment by dlopez-bioinfo** [comment]
Thank you very much for your response! I filtered both files to have the same number of SNPs and now is working like a charm!

**Comment by benoriol** [comment]
Happy to hear this! Don't hesitate to raise another issue if something else comes up.

Thanks for your collaboration,

Benet
